name: build
on: push
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use correct node version
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint functions code
        run: yarn lint:server
      - name: Build server
        run: yarn build:server
      - name: Build dashboard
        run: yarn build:dashboard
      - name: Compile mobile with tsc
        working-directory: mobile
        run: yarn run tsc
      - name: Build android
        run: yarn build:android
