name: build
on: push
defaults:
  run:
    shell: bash
jobs:
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: ./.github/actions/setup
      - run: yarn lint:server
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: ./.github/actions/setup
      - run: yarn build:server
  build-dashboard: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: ./.github/actions/setup
      - run: yarn build:dashboard
  tsc-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: ./.github/actions/setup
      - run: yarn run tsc
        working-directory: mobile
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: ./.github/actions/setup
      - run: yarn build:android
