name: iOS
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: yarn install
    - name: Install mobile dependencies
      working-directory: mobile
      run: yarn install
    - run: xcode-select -p
    - run: cd mobile/ios && pod install
      name: Install pod dependencies
    - name: Build iOS (debug)
      run: "xcodebuild \
        -workspace ios/CompanionKit.xcworkspace \
        -scheme CompanionKit \
        clean archive \
        -sdk iphoneos \
        -configuration Debug \
        -UseModernBuildSystem=NO \
        -archivePath $PWD/CompanionKit \
        CODE_SIGNING_ALLOWED=NO"